### ISSUE TITLE
HeartRate notifications might be masked

### ISSUE THREAD

**Issue by zeroepoch** [mikaelbr/node-heartrate#1]
After playing around with your heartrate module and bluez's gatttool I decided to try using noble directly and I think I found a potential issue with your device setup.  I'm using a Polar H7, which is working fine, unless heartrate measurements are masked by writing zero to the corresponding control descriptor.  My device (and maybe yours as well) remembers the masked state between power cycles so this may not always be necessary.  If for some reason notifications are masked as I did manually using gatttool then you may need to turn them back on before you'll get data read events on the characteristic.  This is different than the notification toggle on the characteristic in noble itself.  I used the following code to do this:

```
characteristic.discoverDescriptors(function(error, descriptors) {
  var data = new Buffer(2);
  data.writeUInt16LE(0x0001, 0);
  var descriptor = descriptors[0];
  descriptor.writeValue(data);
});
```

Ref: https://developer.bluetooth.org/gatt/services/Pages/ServiceViewer.aspx?u=org.bluetooth.service.heart_rate.xml

**Comment by mikaelbr** [comment]
Thanks for your issue and feedback! I'd love to get a pull request for this, if you have the fix ready?

**Comment by zeroepoch** [comment]
I haven't made the change to your code locally I just noticed it while reviewing your code and comparing it to some testing code I wrote.  If I find some extra time I can try to come up with something and send a pull request.

**Comment by zeroepoch** [comment]
I don't even remember now why I filed this ticket and it's been almost 2 years so it's probably safe to just close it out.

**Comment by mikaelbr** [comment]
👍

**Comment by dizag** [comment]
thanks and from me ... after 3 days diggin ... 👍

**Comment by parkerlreed** [comment]
I know this is a long shot, but I may be having the same issue with a Polar OH1.

```
[parker@e55 ~]$ sudo gatttool -b A0:9E:1A:37:D3:9A --char-write-req --handle=0x0027 --value=0100 --listen 
Characteristic Write Request failed: Attribute can't be written
^C
[parker@e55 ~]$ sudo gatttool -b A0:9E:1A:37:D3:9A --char-write-req --handle=0x0027 --value=0001 --listen 
Characteristic Write Request failed: Attribute can't be written
^C
```

27 is UUID 2a37 which I have confirmed is the heart rate notify, I can read it perfectly fine from NRF tools on my phone but computer doesn't want to.

```
handle: 0x0027, char properties: 0x10, char value handle: 0x0028, uuid: 00002a37-0000-1000-8000-00805f9b34fb
```

I do get some data on read but the values never change with heart rate

```
[A0:9E:1A:37:D3:9A][LE]> char-read-hnd 27
Characteristic value/descriptor: 10 28 00 37 2a 
```
