### ISSUE TITLE
Instructions to Fetch UUID in README

### ISSUE THREAD

**Issue by innonate** [mikaelbr/node-heartrate#2]
Hey – perhaps a n00b question here, but I can't for the life of me figure out how you uncover the UUID. Could you consider updating the README with some basic instructions on this matter or point to a resource?

Thanks!

**Comment by mikaelbr** [comment]
It's covered as a part of the API with example, but I don't know if it's clear enough? Does this work for you: https://github.com/mikaelbr/node-heartrate#blehrlistprint-static

**Comment by innonate** [comment]
Thanks, that did work. To be honest I started reading and saw that I needed the UUID and it sent me off looking elsewhere. If I had read below it would have been there! Thanks.
